name: Release

on:
  push:
    tags:
      - '**'

jobs:
  package:
    name: Build dist packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install build tools
        run: python -m pip install --upgrade pip build

      - name: Build package
        run: python -m build

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}"

      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: dist-packages
          path: dist/

  pypi-publish:
    name: Upload packages to PyPI
    needs: package
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/cpknextgen
    permissions:
      id-token: write
    steps:
      - name: Download all the dists packages
        uses: actions/download-artifact@v3
        with:
          name: dist-packages
          path: dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
